volumes:
  flaskdev_data: {}

networks:
  flaskdevweb:

services:
  flaskdevpgdb:
    image: postgres:16.1
    container_name: flaskdevpgdb
    volumes:
      - flaskdev_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - flaskdevweb

  flaskdevapi:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: flaskdev:0.1.0
    container_name: flaskdevapi
    restart: unless-stopped
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - flaskdevpgdb
      - admin
    networks:
      - flaskdevweb

  admin:
    image: dpage/pgadmin4:7.4
    container_name: flaskdevdbadmin
    depends_on:
      - flaskdevpgdb
    environment:
      - PGADMIN_DEFAULT_EMAIL=touchstone@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5100:80
    networks:
      - flaskdevweb
