services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: flaskprod
    restart: unless-stopped
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - "5000:5000"
