networks:
  flaskproweb:

services:
  db:
    build: 
      context: .
      dockerfile: docker/postgres/Dockerfile
    image: flaskpropgdb:0.1.0
    container_name: flaskpropgdb
    env_file: .env
    networks:
      - flaskproweb

  app:
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    image: flaskpro:0.1.0
    env_file: .env
    container_name: flaskproapi
    depends_on:
      - db
    networks:
      - flaskproweb

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: nginxserver:0.1.0
    container_name: flaskpronginx
    ports:
      - 8000:80
    depends_on: 
      - app
    networks:
      - flaskproweb