"""_1_unique_user_email

Revision ID: a7bacd94ce57
Revises: 038ef5e89e9a
Create Date: 2024-07-03 11:57:30.925912

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a7bacd94ce57'
down_revision = '038ef5e89e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_email_UC1', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_email_UC1', type_='unique')

    # ### end Alembic commands ###
